### ISSUE TITLE
Installation setup run forever

### ISSUE THREAD

**Issue by leemengtw** [Bamieh/jupyterlab-clipboard#1] opened 2018-07-10 00:59 UTC
Thanks for making this extension!
However, I got problem when try to install using the command

```
jupyter labextension install jupyterlab-clipboard
```

The install process keep running on 

```
info No lockfile found.
[1/4] 🔍  Resolving packages...
⡀ jupyterlab-clipboard@file:../extensions/jupyterlab-clipboard-0.2.1.tgz
```

forever and I don't know how to solve this issue.

The full traceback is as followed:

```
$ jupyter labextension install jupyterlab-clipboard
> /usr/local/bin/npm pack jupyterlab-clipboard
npm notice
npm notice 📦  jupyterlab-clipboard@0.2.1
npm notice === Tarball Contents ===
npm notice 1.2kB package.json
npm notice 1.2kB README.md
npm notice 93B   lib/clipboard.d.ts
npm notice 670B  lib/clipboard.js
npm notice 232B  lib/dialogs.d.ts
npm notice 2.2kB lib/dialogs.js
npm notice 487B  lib/image-editor.d.ts
npm notice 6.1kB lib/image-editor.js
npm notice 129B  lib/index.d.ts
npm notice 5.2kB lib/index.js
npm notice === Tarball Details ===
npm notice name:          jupyterlab-clipboard
npm notice version:       0.2.1
npm notice filename:      jupyterlab-clipboard-0.2.1.tgz
npm notice package size:  4.9 kB
npm notice unpacked size: 17.6 kB
npm notice shasum:        5892ec3c868d2efe2fc2647e94ec1ed7dc09bfce
npm notice integrity:     sha512-MNpaN5o0iTvT4[...]fwGslLbIjyEdQ==
npm notice total files:   10
npm notice
jupyterlab-clipboard-0.2.1.tgz
> node /Users/meng.lee/anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
(node:43616) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] 🔍  Resolving packages...
⢀ jupyterlab-clipboard@file:../extensions/jupyterlab-clipboard-0.2.1.tgz
```

**Comment by Bamieh** [comment] 2018-07-10 13:25
@leemengtaiwan you're welcome :)

Npm was able to detect the package, but it is failing to resolve it for some reason. I suspect it is a problem reaching the package repository due to connection issues or high latency.

I have published a new version where i removed an unused dependency. I tested installing it locally and it worked fine, so it is worth it if you give it another try.

**Comment by Will-So** [comment] 2018-07-10 20:46
Thanks again for doing this. I'm suffering from the same issue right now as well. I tried deleting everything `/jupyter/lab/extensions` but that didn't help.

**Comment by Bamieh** [comment] 2018-07-10 22:05
@Will-So thanks for reporting, i'll try to investigate again

**Comment by Bamieh** [comment] 2018-07-10 22:09
@Will-So Can you try with this new version? `0.2.3`, I am unable to reproduce it locally so I have to rely on you guys, sorry ❤️ .


Oh maybe it has to do with jupyterlab version. What version of jupyterlab are you using?? I am using version `0.32.1` with jupyter version `4.4.0`

you can know that by typing:

```
$ jupyter lab --version
$ jupyter --version
```

**Comment by leemengtw** [comment] 2018-07-11 01:22
@Bamieh I have the exact same version with you:
```
$ jupyter lab --version
0.32.1
$ jupyter --version
4.4.0
```

The issue occur still, except that with the newer version `0.2.3`:

```
[1/4] 🔍  Resolving packages...
⠠ jupyterlab-clipboard@file:../extensions/jupyterlab-clipboard-0.2.3.tgz
```

Any other advice is appreciated.

**Comment by Bamieh** [comment] 2018-07-11 14:49
So i looked this problem up and it seems that it is the **node version with yarn** might be causing the issue:

links:
- https://github.com/jupyter-widgets/ipywidgets/issues/2061#issuecomment-386166503
- https://github.com/jwkvam/jupyterlab-vim/issues/47
- https://github.com/jupyterlab/jupyter-renderers/issues/131
- https://github.com/jupyter-widgets/ipywidgets/issues/2061#issuecomment-386135340

You probably need to downgrade node or upgrade to get it to work properly, if that is the case, this issue is not related to this extension per say.

**Comment by MLKaufman** [comment] 2018-07-13 17:58
Had the same issue.  I fixed by going into the jupyterlab folder within site-packages and editing .yarnrc
Change the path to yarn to its full static path.

**Comment by leemengtw** [comment] 2018-07-14 16:17
@Bamieh I follow the instruction [here](https://github.com/jupyter-widgets/ipywidgets/issues/2061#issuecomment-397117346) and now the extension work perfectly. 

Since it's node issue, we can close the issue if you want 👍

**Comment by Bamieh** [comment] 2018-07-14 21:23
@leemengtaiwan perfect!

**Closed as completed by Bamieh** 2018-07-14 21:23 UTC
Labels: bug, needs-feedback
